"""materia_banco

Revision ID: 099d86aa5d0d
Revises: dd44a181d7fc
Create Date: 2026-08-02 17:09:03.230911

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "099d86aa5d0d"
down_revision: Union[str, Sequence[str], None] = "dd44a181d7fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materia",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "banco",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("materia_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["materia_id"],
            ["materia.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("materia_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("banco")
    op.drop_table("materia")
    # ### end Alembic commands ###
