"""identidad usuarios y comisiones

Revision ID: 0a0e4595d5cc
Revises: 696c5efea732
Create Date: 2026-07-21 11:32:19.588781

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a0e4595d5cc"
down_revision: str | Sequence[str] | None = "696c5efea732"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usuario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "administrador",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "docente",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "estudiante",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("materia", sa.String(length=200), nullable=False),
        sa.Column("horario", sa.String(length=200), nullable=False),
        sa.Column("administrador_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["administrador_id"],
            ["administrador.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comision_docentes",
        sa.Column("comision_id", sa.UUID(), nullable=False),
        sa.Column("docente_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comision_id"],
            ["comision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["docente_id"],
            ["docente.id"],
        ),
        sa.PrimaryKeyConstraint("comision_id", "docente_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comision_docentes")
    op.drop_table("comision")
    op.drop_table("estudiante")
    op.drop_table("docente")
    op.drop_table("administrador")
    op.drop_table("usuario")
    # ### end Alembic commands ###
