"""invitacion

Revision ID: 479b36fd0759
Revises: 0a0e4595d5cc
Create Date: 2026-07-22 11:43:50.997202

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "479b36fd0759"
down_revision: Union[str, Sequence[str], None] = "0a0e4595d5cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitacion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("comision_id", sa.UUID(), nullable=False),
        sa.Column("docente_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("generada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usada_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["comision_id"],
            ["comision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["docente_id"],
            ["docente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invitacion")
    # ### end Alembic commands ###
