"""estudiante_comision_id

Revision ID: dd44a181d7fc
Revises: 479b36fd0759
Create Date: 2026-07-23 10:32:25.442079

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd44a181d7fc"
down_revision: Union[str, Sequence[str], None] = "479b36fd0759"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("estudiante", sa.Column("comision_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "estudiante", "comision", ["comision_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "estudiante", type_="foreignkey")
    op.drop_column("estudiante", "comision_id")
    # ### end Alembic commands ###
